### ISSUE TITLE
Syntax of links not recognized

### ISSUE THREAD

**Issue by triska** [openssl/web#4]
In the latest [blog entry](https://www.openssl.org/blog/blog/2017/02/21/threads/), there are several links that are probably not rendered as intended, for example:

-  "[crypto/th-lock.c][https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/crypto/threads/th-lock.c]"
- "[crypto/threads_win.c][https://github.com/openssl/openssl/blob/OpenSSL_1_1_0-stable/crypto/threads_win.c#L25]"
- "[test/crltest.c][https://github.com/richsalz/openssl/blob/master/test/crltest.c#L284]"

to name only a few of these fragments, cited verbatim.

**Comment by levitte** [comment]
Fixed.  Should appear in a few minutes.

**Comment by triska** [comment]
It's now more than 22 hours later, and the issue remains. Please check. Thank you!

**Comment by levitte** [comment]
Errrr, I just had myself a look at [the blog entry](https://www.openssl.org/blog/blog/2017/02/21/threads/), and it looks fine to me.  Perhaps if you clear your cache?

**Comment by triska** [comment]
I have cleared the cache and also tried the site with a completely different browser, and still almost all links of this blog&nbsp;entry are distorted in this way.

**Comment by levitte** [comment]
Hmm, didn't 3890c778b5788922df7fa4a0620b9ac757c3a7a9 fix it?

**Comment by levitte** [comment]
Oh, you're looking at the file here on github, aren't you?  It seems the latest didn't get mirrored...

**Comment by levitte** [comment]
Never mind that last comment (now removed), since we don't mirror the blog repo...

**Comment by levitte** [comment]
Suffice to say that we seems to see different things.  I have no idea where you're looking, the links look fine to me now.

**Comment by triska** [comment]
Here is the issue demonstrated with `wget`:

    wget https://www.openssl.org/blog/blog/2017/02/21/threads/ -O - | grep crltest

yielding:

<pre>
<b>[test/crltest.c]</b>[&lt;a href="https://github.com/richsalz/openssl/blob/master/test/crltest.c#L284"&gt;https://github.com/richsalz/openssl/blob/master/test/crltest.c#L284&lt;/a&gt;]
</pre>

The **expected** output is a link of the form:

<pre>
&lt;a href="https://github.com/richsalz/openssl/blob/master/test/crltest.c#L284"&gt;<b>test/crltest.c</b>&lt;/a&gt;
</pre>

**Comment by levitte** [comment]
Ok, I'm seeing it now.  It looks like the frontend lost the last data update, I've given it a kick just now.  I hope to see an updated page again in a few minutes.

**Comment by levitte** [comment]
There.  Looks better to you too?
